<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchPosts()
    {
        // tried to avoid unnecessary join to comments here..
        $Query = $this->createQueryBuilder('p')->getQuery();

        return $Query->getResult();
    }

}
